workflows:
  ios-workflow:
    name: Build & Deploy iOS (TestFlight)
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic TILA
    environment:
      node: 20.18.0
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: ci.tila.app
    scripts:
      - name: Installer les dépendances npm
        script: |
          npm install --legacy-peer-deps

      - name: Préparer le projet Expo (Prebuild)
        script: |
          npx expo prebuild --platform ios --clean

      - name: Installer les Pods CocoaPods
        script: |
          cd ios
          pod install

      - name: Appliquer les profils de signature
        script: |
          xcode-project use-profiles --project ios/TILA.xcodeproj

      - name: Compiler le package iOS signé (.IPA)
        script: |
          xcode-project build-ipa \
            --workspace "ios/TILA.xcworkspace" \
            --scheme "TILA"

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
